### ISSUE TITLE
2 | Add Two Numbers | Python

### ISSUE THREAD

**Issue by pranavaddepalli** [noisefilter19/LeetCode_Algorithms#117]
Problem name: Add Two Numbers
Difficulty: Medium
Language: Python

If this could be assigned to me, that would be great.

**Comment by eg180** [comment]
Interested in this. I am really trying to find my first 'hacktoberfest' labeled issue! Thank you.

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
