### ISSUE TITLE
2 | Add Two Numbers | Java

### ISSUE THREAD

**Issue by pranavaddepalli** [noisefilter19/LeetCode_Algorithms#118]
Problem name: Add Two Numbers
Difficulty: Medium
Language: Java

I've also completed this problem in Java. If this could be assigned to me, that would also be great.

**Comment by tanushree57** [comment]
I've solved this one. If you could kindly check the PR I've submitted for this issue

**Comment by arpita2712** [comment]
Please assign this to me . I have solution ready.

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
