### ISSUE TITLE
1447 | Simplified Fractions | Python

### ISSUE THREAD

**Issue by iamsnj** [noisefilter19/LeetCode_Algorithms#127]
Problem name: Simplified Fractions
Difficulty: Medium
Language: Python

**Comment by iamsnj** [comment]
Please assign this issue to me.
Thanks :)

**Comment by ankitsri1998** [comment]
Please Assign this to me, I can do this efficiently.
Thank You.

**Comment by iamsnj** [comment]
@ankitsri1998 you can take other problem, as I have raised the issue first.
I hope you get it.
Thanks :)
