### ISSUE TITLE
19 | Remove Nth Node From End of List | C++

### ISSUE THREAD

**Issue by gaurav7019** [noisefilter19/LeetCode_Algorithms#138]
Problem name: Remove Nth Node From End of List
Difficulty: Medium
Language: C++

**Comment by ByteCode-Test** [comment]
Sir please Assign this to me , i can resolve it.
thank you

**Comment by kaunik07** [comment]
I would like to solve this , Please assign it to me

**Comment by gaurav7019** [comment]
@ByteCode-Test  @kaunik07  Read Contribution Guidelines first.

**Comment by ByteCode-Test** [comment]
@gaurav7019 Sir i have read the guidelines now you can assign me.
Problem No. 19  | Remove Nth Node From End of List  | C++

**Comment by kaunik07** [comment]
> @ByteCode-Test @kaunik07 Read Contribution Guidelines first.

Yes sir , I have read and solving new problem . Thank You

**Comment by gaurav7019** [comment]
@noisefilter19 Check #195
