### ISSUE TITLE
1111 | Maximum Nesting Depth of Two Valid Parentheses Strings | C++

### ISSUE THREAD

**Issue by hardik7e** [noisefilter19/LeetCode_Algorithms#167]
Problem name: Maximum Nesting Depth of Two Valid Parentheses Strings
Difficulty: Medium
Language: C++

**Comment by hardik7e** [comment]
Please assign this problem to me

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
