### ISSUE TITLE
1395 | Count Number of Teams | Python

### ISSUE THREAD

**Issue by Harivind** [noisefilter19/LeetCode_Algorithms#173]
Problem name: Count Number of Teams    
Difficulty: Medium
Language: Python

**Comment by Harivind** [comment]
Please assign me to this issue !

**Comment by Kadermiyanyedi** [comment]
Can you assign me to this issue for c++?

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
