### ISSUE TITLE
84 | Largest Rectangle in Histogram | cpp

### ISSUE THREAD

**Issue by vikas9905** [noisefilter19/LeetCode_Algorithms#215]
Problem name:Largest Rectangle in Histogram
Difficulty:Hard
Language:CPP

**Comment by AbhishekTiwari07** [comment]
please assign this to me

**Comment by Saharsh979** [comment]
Please assign this to me

**Comment by sbm1arora** [comment]
could you assign this to me ?

**Comment by noisefilter19** [comment]
@sbm1arora This is already solved

**Comment by sbm1arora** [comment]
ok
