### ISSUE TITLE
About pullrequests

### ISSUE THREAD

**Issue by grpnpraveen** [noisefilter19/LeetCode_Algorithms#217]
I made a pull request before two days and in the hacktoberfest site, it also showed that. But, today in the site it's showing that no pull requests are made. 
anyone help me.

**Comment by grpnpraveen** [comment]
oh ok

**Comment by noisefilter19** [comment]
@grpnpraveen I don't see any issue assigned to you. Please read the contribution guidelines before raising a PR. I'm the only maintainer for this repo and it's tough to look into all PR's so I'm going only over the issues assigned.
@kaash-bot I might have missed your issue. There are many first time contributors, that I'm giving priority to. Please don't take it as an easy opportunity to score a few PR's for hacktoberfest.
