### ISSUE TITLE
6 | ZigZag Conversion | Python

### ISSUE THREAD

**Issue by UdeshAthukorala** [noisefilter19/LeetCode_Algorithms#221]
Problem name: ZigZag Conversion
Difficulty: Medium
Language: Python

**Comment by UdeshAthukorala** [comment]
@noisefilter19  I'd like to work on this problem. Can you please assign it to me?

**Comment by noisefilter19** [comment]
I suppose this has been added already

**Comment by UdeshAthukorala** [comment]
Thank you.
