### ISSUE TITLE
5 | Longest Palindromic Substring | C

### ISSUE THREAD

**Issue by ofekMula** [noisefilter19/LeetCode_Algorithms#227]
Problem name: Longest Palindromic Sequence
Difficulty: Medium.
Language: C.

please assign to me this problem.

**Comment by basharfarid77** [comment]
Would be happy to contribute if assigned :)

**Comment by ofekMula** [comment]
It seems that there is already an implementation of this problem in Python.
so I wish to implement it in C.

**Comment by noisefilter19** [comment]
Cool. Thanks
