### ISSUE TITLE
350 | Quick-Sort Algorithim | Python3.8

### ISSUE THREAD

**Issue by JaniniRami07** [noisefilter19/LeetCode_Algorithms#238]
Problem name: Quick-Sort Algorithm visualized in Matplotlib.
Difficulty: Medium
Language: Python3.8

I would like to assign this problem to myself.

**Comment by Achyut-sudo** [comment]
hey @JaniniRami07  can you assign this to me ???

**Comment by JaniniRami07** [comment]
Only @noisefilter19 can assign this, And sorry I would like it to be assigned to me as written above!

**Comment by noisefilter19** [comment]
@JaniniRami07 This doesn't seem to be a leetcode problem. Athough I would've merged it, it wouldn't be appropriate for the content this repository hosts. If you want you can open a new issue and tag this issue so I can assign it to you

**Comment by JaniniRami07** [comment]
I have been assigned with this issue (quick sorting algorithm) but I couldnt clone the repo because of the error, anyways it turns out to be a problem with my git version its all good and working and I am probably going to submit my pull request today!
