### ISSUE TITLE
1352 | Product of the last k numbers | Python3

### ISSUE THREAD

**Issue by DasithEdirisinghe** [noisefilter19/LeetCode_Algorithms#294]
Problem name:product of the last k numbers
Difficulty:medium
Language:python3
link : https://leetcode.com/problems/product-of-the-last-k-numbers/

Please assign me.I like to work on this problem

**Comment by ravireddy07** [comment]
I would like to work on this... Assign to me..!!!

**Comment by DasithEdirisinghe** [comment]
@noisefilter19 do this need to add hacktoberfest-accepted label in order to mark as a complete pull request.
