### ISSUE TITLE
713 | Subarray Product Less Than K | Python

### ISSUE THREAD

**Issue by RedHeadphone** [noisefilter19/LeetCode_Algorithms#299]
Problem name: Subarray Product Less Than K
Difficulty: Medium
Language: Python

**Comment by obaoba96** [comment]
I would like to work on this, can you assign this to me?

**Comment by RedHeadphone** [comment]
plz assign it to me

**Comment by Swadha-27** [comment]
Problem name: Subarray Product Less Than K
Difficulty: Medium
Language: Python

Please assign.
