### ISSUE TITLE
1578 | Minimum Deletion Cost to Avoid Repeating Letters | CPP

### ISSUE THREAD

**Issue by su-madeye** [noisefilter19/LeetCode_Algorithms#30]
Hey I would like to contribute to the repo by adding the CPP solution to the problem Minimum Deletion Cost to Avoid Repeating Letters of leetcode. If already not assigned it to anyone, please assign it to me.

Problem name: Minimum Deletion Cost to Avoid Repeating Letters
Difficulty: Medium
Language: C++

**Comment by noisefilter19** [comment]
Go ahead
