### ISSUE TITLE
360 | Dictionary Attack | Python

### ISSUE THREAD

**Issue by atshaya-anand** [noisefilter19/LeetCode_Algorithms#306]
Problem name: Dictionary Attack Algorithm
Difficulty: Medium
Language: Python

**Comment by ashvinimore** [comment]
Hello,
Could you please elaborate the problem.
So,I could understand it properly.
Thank You

**Comment by atshaya-anand** [comment]
Sure, So basically a dictionary attack uses a word list, which is a predefined list of words, and each word in the list is hashed. If the cracking person/software matches the hash output from the dictionary attack to the password hash, the attacker has successfully identified the original password.
I have the solution for this problem. Please Assign this to me.
