### ISSUE TITLE
98 | Validate Binary Search Tree | Python

### ISSUE THREAD

**Issue by RedHeadphone** [noisefilter19/LeetCode_Algorithms#368]
Problem name: Validate Binary Search Tree
Difficulty: Medium
Language: Python

**Comment by 1sarthakbhardwaj** [comment]
I would like to contribute here, please assign it to me

**Comment by RedHeadphone** [comment]
I would like to it myself , sorry
waiting for getting assigned

**Comment by 1sarthakbhardwaj** [comment]
ok no issue :)
