### ISSUE TITLE
189 | Rotate Array | python

### ISSUE THREAD

**Issue by saurabh-172** [noisefilter19/LeetCode_Algorithms#38]
hi, I'm new to open source contribution and hacktoberfest but I have read your contribution guidelines and I would like to contribute to this repo by adding python solution to the problem Rotate Array of LeetCode. Please assign this to me if not assigned to anyone. 
I also had a doubt that are we allowed to use the built-in function in algorithm questions like if the question is to sort then except sort() built-in function am I allowed to use other functions like insert, pop. I asked since I'm still learning algorithms and since this repo is for education purpose I thought this would be a great opportunity to learn also. Please forgive me if I have asked some wrong questions or questions which should not be asked. 

Problem name: Rotate Array
Difficulty: medium
Language: python

**Comment by noisefilter19** [comment]
Hey, you can use any standard library provided by the language. Also, make sure that the solutions are accepted on leetcode. I've assigned the issue to you

**Comment by saurabh-172** [comment]
thanks for assigning me and clearing my doubts. Accordingly, I have made PR please check #38
