### ISSUE TITLE
75. | Sort Colors | C++

### ISSUE THREAD

**Issue by sourabhmandal** [noisefilter19/LeetCode_Algorithms#384]
Problem name: Sort Colors
Difficulty: Medium
Language: cpp

**Comment by sourabhmandal** [comment]
I have created a pull request please review

**Comment by noisefilter19** [comment]
Read Contribution Guidelines

**Comment by sourabhmandal** [comment]
Hi @noisefilter19 . I have amended the changes and created a new PR #581 . Please review
