### ISSUE TITLE
390 | Merge sorting algorithm| c++

### ISSUE THREAD

**Issue by Banseedhar01** [noisefilter19/LeetCode_Algorithms#407]
Problem name:Merge Algorithm
Difficulty:medium
Language:c++

**Comment by 13snehitha** [comment]
@noisefilter19 
Can you assign this to me, I'd like to work on this issue.

**Comment by Sourabh025** [comment]
Can i work in it ?

**Comment by Banseedhar01** [comment]
i already have a solution for this problem.

**Comment by noisefilter19** [comment]
Irrelevant issue. This is a repo meant for leetcode solutions
