### ISSUE TITLE
129. | Sum Root to Leaf Numbers | C++

### ISSUE THREAD

**Issue by jjjding2** [noisefilter19/LeetCode_Algorithms#412]
Problem name: [Sum Root to Leaf Numbers](https://leetcode.com/problems/sum-root-to-leaf-numbers/)
Difficulty: Medium
Language: C++

I would love to attempt this problem.

**Comment by Ruchi101** [comment]
Please assign this to me. Thanks.

**Comment by jjjding2** [comment]
@Ruchi101 I have already created a pull request fixing this issue (as mentioned above).

**Comment by jjjding2** [comment]
@noisefil
