### ISSUE TITLE
6 | ZigZag Conversion | Python3

### ISSUE THREAD

**Issue by therohanrao** [noisefilter19/LeetCode_Algorithms#452]
Problem name: ZigZag Conversion
Difficulty: Medium
Language: Python 3

**Comment by therohanrao** [comment]
I have a solution ready for this problem

**Comment by UdeshAthukorala** [comment]
@therohanrao Hi, My solution is already committed and merged to the repository. So can you please select another problem? :)

**Comment by therohanrao** [comment]
> @therohanrao Hi, My solution is already committed and merged to the repository. So can you please select another problem? :)

Whoops didn't see that. Will do!
