### ISSUE TITLE
75 | Sort Colors | Python

### ISSUE THREAD

**Issue by Muskan0** [noisefilter19/LeetCode_Algorithms#497]
Problem name: Sort Colors
Difficulty: Medium
Language: Python

**Comment by Swadha-27** [comment]
I would like to work on this problem.
Please assign me this.

**Comment by Swadha-27** [comment]
Problem name: Sort Colors
Difficulty: Medium
Language: Python

**Comment by Muskan0** [comment]
@muskanvk  @Swadha-27 Please read the contributing guidelines first.
