### ISSUE TITLE
78 | Subsets | Java

### ISSUE THREAD

**Issue by Sanatan-Shrivastava** [noisefilter19/LeetCode_Algorithms#511]
Problem name: Subsets
Difficulty: Medium
Language: Java

**Comment by anirudherabelly** [comment]
assign it to me!

**Comment by Sanatan-Shrivastava** [comment]
Leetcode 78 - Subsets submitted in Java, please check the PR.

**Comment by jntushar** [comment]
Assign this to me

**Comment by Sanatan-Shrivastava** [comment]
@noisefilter19 Please assign this to me
