### ISSUE TITLE
31. | Next Permutation | Python

### ISSUE THREAD

**Issue by MohitRustagi** [noisefilter19/LeetCode_Algorithms#558]
Problem name: Next Permutation
Difficulty: Medium
Language: Python

Can you please assign it to me?

**Comment by nomanarshad94** [comment]
Hi,
I want to contribute to it. Please assign this issue to me. I have read the contribution guide and just waiting to be assigned to it so I can open PR!
Thanks.

**Comment by ambrish-02** [comment]
Hey! I want to work on this issue. Can I go ahead?

**Comment by MohitRustagi** [comment]
@noisefilter19 There is already an existing python solution for this problem.
