### ISSUE TITLE
Problem No. | Articulation Point and Bridges points | C++

### ISSUE THREAD

**Issue by Error404m** [noisefilter19/LeetCode_Algorithms#580]
Problem name:  Find Articulation Point and Bridges points in Graph
Difficulty:  MEDIUM
Language:  C++

**Comment by Error404m** [comment]
Thanx a lot @noisefilter19 for assigning, Raised PR #723 .

**Comment by noisefilter19** [comment]
This is not a Leetcode problem if i'm not wrong

**Comment by noisefilter19** [comment]
If so, I can't accept this
