### ISSUE TITLE
22 | Generate Parentheses | Go

### ISSUE THREAD

**Issue by noisefilter19** [noisefilter19/LeetCode_Algorithms#6]
Problem name: Generate Parentheses
Difficulty: Medium
Language: Go

**Comment by amanjain97** [comment]
@noisefilter19 Can I take this issue ?

**Comment by noisefilter19** [comment]
Hey Aman, let's make it one issue at a time. Please complete the other one and then this is all yours

**Comment by amanjain97** [comment]
@noisefilter19 Please review https://github.com/noisefilter19/LeetCode_Algorithms/pull/33

**Comment by grpnpraveen** [comment]
Can I add leetcode in other than python
