### ISSUE TITLE
560 | Subarray Sum Equals K | Python

### ISSUE THREAD

**Issue by nomanarshad94** [noisefilter19/LeetCode_Algorithms#605]
Problem name: Subarray Sum Equals K
Difficulty: Medium
Language: Python

**Comment by nomanarshad94** [comment]
Hi,
Please assign this issue to me. 
Thanks.

**Comment by Jahnavi-Jonnalagadda** [comment]
Sir, Could you please assign this issue to me?

**Comment by nomanarshad94** [comment]
#718  
Created pull request please review and merge it.
