### ISSUE TITLE
8 | String to Integer (atoi) | Python

### ISSUE THREAD

**Issue by qf-jonathan** [noisefilter19/LeetCode_Algorithms#65]
Problem name: String to Integer (atoi)
Difficulty: Medium
Language: Python

**Comment by Vpingdevil** [comment]
I can submit this solution.. Please assign me

**Comment by Vpingdevil** [comment]
can I submit pull request??

**Comment by qf-jonathan** [comment]
@Vpingdevil I think you need to read the [Contribution Guidelines](https://github.com/noisefilter19/LeetCode_Algorithms/blob/main/CONTRIBUTION.md) first

**Comment by Vpingdevil** [comment]
You mean, I've to raise an issue for the problem I've to contribute..
If so, Thank you!!

**Comment by noisefilter19** [comment]
@qf-jonathan Go ahead!

**Comment by maxily1** [comment]
Wait, Is the mission just to convert a string to integer?
If so, I would like to work on this.
