### ISSUE TITLE
79 | Word Search | Python

### ISSUE THREAD

**Issue by devansh-07** [noisefilter19/LeetCode_Algorithms#653]
Problem name: Word Search
Difficulty: Medium
Language: Python

**Comment by devansh-07** [comment]
Could you please assign this issue to me?

**Comment by scaredevil227** [comment]
assign this to me please

**Comment by devansh-07** [comment]
Hey @scaredevil227, I want this issue to be assigned to me and that's why I've opened it. You should open a new issue for a new problem.
