### ISSUE TITLE
1 | Palindrome checker | JavaScript

### ISSUE THREAD

**Issue by RoyalTechie** [noisefilter19/LeetCode_Algorithms#684]
Problem name: Palindrome Checker
Difficulty: Medium
Language: Javascript

It will be my first pull request (problem no.=1)
If there is anything wrong, i will make sure to Fix it...

**Comment by gill876** [comment]
Just make a JS function?

**Comment by RoyalTechie** [comment]
@gill876 Actually i already created the JS function for it but asking for permission to create pull request.

**Comment by gill876** [comment]
> @gill876 Actually i already created the JS function for it but asking for permission to create pull request.
> 

Oooh ohh I see
