### ISSUE TITLE
21 | Merge Two Sorted Lists| Python3

### ISSUE THREAD

**Issue by mohinesh9999** [noisefilter19/LeetCode_Algorithms#692]
Problem name: Merge Two Sorted Lists
Difficulty: Easy
Language: Python 

please assign it to me

**Comment by yoki-07** [comment]
I want to contribute in this. Can you please assign me this issue. @mohinesh9999

**Comment by mohinesh9999** [comment]
successfully added pr please review it @noisefilter19 #717
