### ISSUE TITLE
1007 | Minimum Domino Rotations For Equal Row | Python

### ISSUE THREAD

**Issue by kakashi215** [noisefilter19/LeetCode_Algorithms#694]
Problem name: Minimum Domino Rotations For Equal Row
Difficulty: Medium
Language: Python

![Minimum Domino Rotations For Equal Row](https://user-images.githubusercontent.com/34543293/96499773-7cd3fb80-126b-11eb-8d3c-011adb4251ee.JPG)

This problem is very interesting and I am working on it.
Could I contribute my solution to this repository?

P.S. Thanks for this amazing repo!! Kudos.

**Comment by kakashi215** [comment]
Hey @noisefilter19 there seems to be some problem with the file 1352 | Product of the last k numbers.py in the Python folder. 
Windows can't accept '|' in file names hence it won't let you clone the repo. Tried using git clone as well as Github desktop app.
So I rectified the file name to allow me to work on it.
Would that be comfortable? 

Regards.

**Comment by noisefilter19** [comment]
Hey thanks for making those changes

**Comment by kakashi215** [comment]
> Hey thanks for making those changes

My pleasure. Allow me to contribute more. @noisefilter19
