### ISSUE TITLE
224. | Basic Calculator |Python

### ISSUE THREAD

**Issue by kakashi215** [noisefilter19/LeetCode_Algorithms#701]
Problem name: Basic Calculator
Difficulty: Hard
Language: Python
![Basic Calculator](https://user-images.githubusercontent.com/34543293/96545657-7161ee00-12c6-11eb-9e2e-9656706708dd.JPG)

Requesting to be assigned to this task @noisefilter19 .

Happy Coding!

**Comment by DanialAnsari** [comment]
I am interested in this issue and would like to work on it.

**Comment by kakashi215** [comment]
Hey @DanialAnsari appreciate your help.
I think the better way would be to open a new issue of a problem which isn't there in the repo.
That way we'd have much more problems covered.
