### ISSUE TITLE
179. | Largest Number | Python

### ISSUE THREAD

**Issue by MohitRustagi** [noisefilter19/LeetCode_Algorithms#709]
Problem name: Largest Number
Difficulty: Medium
Language: Python

Very good problem. I see no existing solution. Can you please assign it to me?

**Comment by Bhavesh27** [comment]
@MohitRustagi Can i work on this. Can you assign me this?

**Comment by ranidu-harshana** [comment]
can you assign me??

**Comment by MohitRustagi** [comment]
#815
