### ISSUE TITLE
103 | Binary Tree Zigzag Level Order Traversal | Python

### ISSUE THREAD

**Issue by neil007m** [noisefilter19/LeetCode_Algorithms#74]
Problem name: Binary Tree Zigzag Level Order Traversal
Difficulty: Medium
Language: Python

**Comment by kalpeshT101** [comment]
assign

**Comment by neil007m** [comment]
Please read [CONTRIBUTING.md](https://github.com/noisefilter19/LeetCode_Algorithms/blob/main/CONTRIBUTION.md)

**Comment by noisefilter19** [comment]
@neil007m Would you like to work on this?

**Comment by noisefilter19** [comment]
@kalpeshT101 Feel free to pick some other issue or open a new one

**Comment by neil007m** [comment]
@noisefilter19 yes. I opened a few other issues as well.

**Comment by noisefilter19** [comment]
@neil007m Please solve one at a time
