### ISSUE TITLE
Rename CONTRIBUTION.md to CONTRIBUTING.md

### ISSUE THREAD

**Issue by jarvisdev** [noisefilter19/LeetCode_Algorithms#77]
According to Hacktoberfest website, the repo should have a contribution guideline file named `CONTRIBUTING.md`

**Comment by noisefilter19** [comment]
Right. But that would be a very small issue to work on and not a quality PR. I'll do that myself. Thanks for pointing it out :)

**Comment by jarvisdev** [comment]
Yeah. Understood. Even I just raised this issue to draw attention. I was not expecting this one for hacktoberfest
