### ISSUE TITLE
4. | Median of Two Sorted Arrays | Python

### ISSUE THREAD

**Issue by Ahkam95** [noisefilter19/LeetCode_Algorithms#81]
Problem name: 4. Median of Two Sorted Arrays
Difficulty: hard
Language: python

**Comment by ZarghamDanial** [comment]
Hey, can i take up this issue?

**Comment by Ahkam95** [comment]
@ZarghamDanial  Actually I 'm interested in this problem and currently developing it. I'm awaiting for the permission to make a PR. 
@amanjain97  please assign me.
BTW sorry @ZarghamDanial. Try another one:)

**Comment by amanjain97** [comment]
@Ahkam95 I am not admin/ maintainer of this repo or issue. Please ask @noisefilter1

**Comment by Ahkam95** [comment]
It was a mistake @amanjain97  :) 
@noisefilter19  please assign me

**Comment by ZarghamDanial** [comment]
Its okay @Ahkam95 , all the best!
