### ISSUE TITLE
54 | Spiral Matrix | Python

### ISSUE THREAD

**Issue by michal-dbrnowski** [noisefilter19/LeetCode_Algorithms#82]
Problem name: 54. Spiral Matrix
Difficulty: Medium
Language: Python

**Comment by michal-dbrnowski** [comment]
Please, assign me to this issue.

**Comment by TheFenrisLycaon** [comment]
I finished it in my PR. #108

**Comment by flick-23** [comment]
I would like to contribute my solution for this problem.
Please assign me if it has not been contributed before.
Hope to here you from soon :)
