### ISSUE TITLE
Problem No: 36 | Problem name: Valid Sudoku | Language: Python

### ISSUE THREAD

**Issue by Rushijaviya** [noisefilter19/LeetCode_Algorithms#866]
Problem name: Valid Sudoku
Difficulty: Medium
Language: Python

**Comment by anushkarthik05** [comment]
Can I do this problem? @Rushijaviya

**Comment by Rushijaviya** [comment]
@anushkarthik05 wait till it assign!

**Comment by anushkarthik05** [comment]
@Rushijaviya Ok

**Comment by anushkarthik05** [comment]
@Rushijaviya I will wait till you assign me.

**Comment by Rushijaviya** [comment]
@anushkarthik05 You are on wrong path. I am not the one who can assign this. By the way I am requesting to assign this problem to me by creating this issue.  Please read the [Contribution Guidelines](./CONTRIBUTING.md).

**Comment by Rushijaviya** [comment]
@anushkarthik05 In case you want to contribute in open source you can contribute here. [https://github.com/Rushijaviya/Mezzo-Projects]
