### ISSUE TITLE
41 | First Missing Positive | Python3

### ISSUE THREAD

**Issue by TheFenrisLycaon** [noisefilter19/LeetCode_Algorithms#874]
Problem name: First Missing Positive
Difficulty: Hard
Language: Python3

**Comment by nikita9604** [comment]
Hi, I can provide code for this problem. Could you please assign this issue to me?

**Comment by TheFenrisLycaon** [comment]
Read contribution guidelines

**Comment by nikita9604** [comment]
Ok got it. Thanks for the info

**Comment by TheFenrisLycaon** [comment]
@noisefilter19 please check.
