### ISSUE TITLE
41 | First Missing Positive | C++

### ISSUE THREAD

**Issue by noisefilter19** [noisefilter19/LeetCode_Algorithms#9]
Problem name: First Missing Positive
Difficulty: 41
Language: C++

**Comment by amanjain97** [comment]
@noisefilter19 Can I take this.

**Comment by JackTNorris** [comment]
Already submitted PR

**Comment by noisefilter19** [comment]
@JackTNorris please read the contribution guidelines before submitting the PR.

**Comment by noisefilter19** [comment]
please take up an existing issue or open a new issue and wait for the assignment @JackTNorris

**Comment by amanjain97** [comment]
@noisefilter19 Please review https://github.com/noisefilter19/LeetCode_Algorithms/pull/14
Thanks

**Comment by noisefilter19** [comment]
@JackTNorris have merged your solution as well as it took a slight different approach.

**Comment by JackTNorris** [comment]
@noisefilter19 So sorry! Kinda new to this. I will make sure to do that next time
