### ISSUE TITLE
65. | Valid Number | C++

### ISSUE THREAD

**Issue by agrawal-deeksha** [noisefilter19/LeetCode_Algorithms#935]
Problem name: Valid Number
Difficulty: Hard
Language: C++

**Comment by Zaid23** [comment]
Hey @agrawal-deeksha  I would Like to take this up, assign it to me

**Comment by agrawal-deeksha** [comment]
Hi @Zaid23, Please read the contribution guidelines. If you need to create a PR, raise an issue for the same. You will get assigned to your issue.
