### ISSUE TITLE
68. | Text Justification | C++

### ISSUE THREAD

**Issue by agrawal-deeksha** [noisefilter19/LeetCode_Algorithms#936]
Problem name: Text Justification
Difficulty: Hard
Language: C++

**Comment by Zaid23** [comment]
Hey @agrawal-deeksha, I would like to do it. assign it to me

**Comment by agrawal-deeksha** [comment]
Hi @Zaid23, Please read the contribution guidelines. If you need to create a PR, raise an issue for the same. You will get assigned to your issue.
