### ISSUE TITLE
19 | Remove Nth Node From End of List | Java

### ISSUE THREAD

**Issue by truthfool** [noisefilter19/LeetCode_Algorithms#955]
Problem name: Remove Nth Node From End of List
Difficulty: Medium
Language: Java

**Comment by Pretty-19** [comment]
@truthfool  can you assign this issue to me?

**Comment by truthfool** [comment]
@Pretty-19 actually im waiting for the contributors to assign it to me.Please read the contribution guidelines : https://github.com/noisefilter19/LeetCode_Algorithms/blob/main/CONTRIBUTING.md

**Comment by Pretty-19** [comment]
okay got that

**Comment by shrutigore** [comment]
I'm interested in working on this issue, please assign it to me!
